version: "3"
services:
  screenshot:
    image: tons/surf-ais-screenshot:1.0.0-SNAPSHOT
    env_file:
      - .env
    volumes:
      - ./data:/data
    depends_on:
      - selenium

  selenium:
    image: selenium/standalone-chrome:4.0.0
    environment:
      SELENIUM_HOST: selenium
      SCREEN_WIDTH: 1920
      SCREEN_HEIGHT: 1080
    # TODO: Remove, don't expose if both services are running in Docker
    ports:
      - 4444:4444
